export type ClassValue = string | false | null | undefined;

export function cn(...classes: ClassValue[]) {
  return classes.filter(Boolean).join(' ');
}

const diagonalInk = '[background-image:repeating-linear-gradient(-15deg,transparent_0,transparent_29px,rgba(20,33,61,.035)_30px,transparent_31px)]';
const diagonalPaper = '[background-image:repeating-linear-gradient(-15deg,transparent_0,transparent_29px,rgba(255,255,255,.045)_30px,transparent_31px)]';
const headingBase = "m-0 max-w-[800px] font-[950] leading-[.79] tracking-[-.085em] uppercase [&_em]:relative [&_em]:not-italic [&_em]:text-signal [&_em]:after:absolute [&_em]:after:-bottom-[7px] [&_em]:after:left-[2%] [&_em]:after:right-[-2%] [&_em]:after:h-[7px] [&_em]:after:-rotate-2 [&_em]:after:bg-signal [&_em]:after:content-['']";
const displayHeading = `${headingBase} text-[clamp(64px,8.6vw,132px)] max-[780px]:text-[clamp(58px,20vw,92px)]`;

export const s = {
  pageBody: 'm-0 bg-paper font-sans text-ink',
  brand: 'flex min-w-0 items-center no-underline',
  displayHeading,
  eyebrow: 'm-0 mb-6 flex items-center gap-[9px] text-[11px] font-black tracking-[.14em] [&>span]:inline-block [&>span]:h-1 [&>span]:w-[25px] [&>span]:bg-signal',
  eyebrowLight: 'm-0 mb-6 flex items-center gap-[9px] text-[11px] font-black tracking-[.14em] [&>span]:inline-block [&>span]:h-1 [&>span]:w-[25px] [&>span]:bg-paper',
  step: 'm-0 mb-6 text-[11px] font-black tracking-[.13em] text-[#9da6b9]',
  authDialogEyebrow: '!mb-[18px]',
  submissionStep: '!mb-[18px]',
  settingsStep: '!mb-2 !text-[#667085]',
  contactStep: '!mb-0',
  likedBackLink: '!mb-[60px]',
  governmentBackLink: '!mb-[60px]',
  orgHeadingEyebrow: '!mb-[25px]',
  visuallyHidden: 'absolute -m-px h-px w-px overflow-hidden border-0 p-0 whitespace-nowrap [clip:rect(0,0,0,0)]',
  backLink: 'mb-[65px] inline-block text-[10px] font-[950] tracking-[.08em] uppercase underline-offset-[5px] max-[780px]:mb-12',
  headingEndLockup: 'inline-flex items-center whitespace-nowrap align-baseline',
  headingEndStar: 'ml-[.12em] block size-[.74em] object-contain',
  primaryButton: 'mt-[15px] flex min-h-[62px] items-center justify-between bg-signal px-[22px] text-[13px] font-[950] tracking-[.09em] text-white no-underline shadow-[5px_5px_0_var(--color-paper)] transition-[transform,box-shadow] duration-150 hover:translate-[3px] hover:shadow-[2px_2px_0_var(--color-paper)]',
  formSubmit: 'mt-[7px] flex min-h-[58px] items-center justify-between border-0 bg-signal px-[19px] text-[12px] font-[950] tracking-[.09em] text-white no-underline shadow-[5px_5px_0_var(--color-paper)] disabled:cursor-wait disabled:opacity-[.62]',
  formError: '!m-0 border-l-4 border-signal bg-[#fff0f1] px-[14px] py-3 text-[13px] font-extrabold leading-[1.4] !text-[#a81522]',
  formSuccess: 'm-0 border-l-4 border-[#287a3d] bg-[#e7f6e8] px-[14px] py-3 text-[13px] font-extrabold leading-[1.4] text-[#175c2a]',

  siteHeader: 'relative z-[2] grid h-[78px] grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-[18px] border-b-2 border-ink bg-paper px-[5vw] max-[780px]:h-auto max-[780px]:min-h-[116px] max-[780px]:grid-cols-[minmax(0,1fr)_auto] max-[780px]:grid-rows-[auto_auto] max-[780px]:gap-x-[9px] max-[780px]:gap-y-3 max-[780px]:px-[18px] max-[780px]:pt-3 max-[780px]:pb-[14px]',
  headerBrand: 'max-[780px]:col-span-full max-[780px]:justify-self-center [&_img]:block [&_img]:h-12 [&_img]:w-auto max-[780px]:[&_img]:h-10 max-[780px]:[&_img]:max-w-[min(100%,280px)]',
  headerActions: 'flex min-w-0 items-center justify-end gap-[22px] max-[780px]:col-start-2 max-[780px]:row-start-2 max-[780px]:justify-self-end max-[780px]:gap-2',
  submitLink: 'flex min-h-[42px] items-center justify-center whitespace-nowrap bg-signal px-4 text-[11px] font-[950] tracking-[.09em] text-white uppercase no-underline shadow-[4px_4px_0_var(--color-ink)] transition-[transform,box-shadow] duration-150 hover:translate-[2px] hover:shadow-[2px_2px_0_var(--color-ink)] max-[780px]:min-h-[37px] max-[780px]:px-[9px] max-[780px]:text-[9px] max-[780px]:tracking-[.06em]',
  submitLinkFull: 'max-[780px]:hidden',
  submitLinkShort: 'hidden max-[780px]:inline',
  siteSearch: 'relative flex w-[min(340px,36vw)] items-center justify-center justify-self-center max-[780px]:col-start-1 max-[780px]:row-start-2 max-[780px]:w-full max-[780px]:justify-self-stretch',
  siteSearchToggle: 'hidden size-[37px] cursor-pointer place-items-center border-2 border-ink bg-transparent p-0 text-ink [&_svg]:size-[18px] [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-[2.2] [&_svg]:[stroke-linecap:square]',
  siteSearchField: 'relative w-full max-[780px]:z-12 max-[780px]:block max-[780px]:w-full [&_input]:h-[37px] [&_input]:w-full [&_input]:rounded-none [&_input]:border-2 [&_input]:border-ink [&_input]:bg-white [&_input]:px-3 [&_input]:font-sans [&_input]:text-[13px] [&_input]:font-bold [&_input]:text-ink [&_input]:outline-none [&_input]:focus:shadow-[3px_3px_0_var(--color-signal)] [&_input::-webkit-search-cancel-button]:appearance-none',
  siteSearchPanel: 'absolute top-[calc(100%+9px)] left-1/2 z-12 max-h-[min(70vh,460px)] w-[min(420px,calc(100vw-36px))] -translate-x-1/2 overflow-auto border-2 border-ink bg-paper shadow-[6px_6px_0_var(--color-signal)] max-[780px]:left-0 max-[780px]:right-auto max-[780px]:w-full max-[780px]:translate-x-0 [&_button]:grid [&_button]:w-full [&_button]:cursor-pointer [&_button]:gap-1 [&_button]:border-0 [&_button]:border-b [&_button]:border-line [&_button]:bg-transparent [&_button]:px-[14px] [&_button]:py-3 [&_button]:text-left [&_button]:text-ink [&_button:last-child]:border-b-0 [&_button:hover]:bg-ink [&_button:hover]:text-paper [&_button_strong]:text-[14px] [&_button_strong]:font-[950] [&_button_strong]:leading-[1.2] [&_button_span]:text-[12px] [&_button_span]:font-bold [&_button_span]:leading-[1.35] [&_button_span]:text-ink/72 [&_button:hover_span]:text-paper/78',
  searchResultActive: 'bg-ink! text-paper! [&_span]:text-paper/78!',
  siteSearchGroup: '[&+&]:border-t-2 [&+&]:border-ink',
  siteSearchLabel: 'm-0 px-[14px] pt-[10px] pb-[6px] text-[10px] font-[950] tracking-[.1em] text-ink/72 uppercase',
  siteSearchStatus: 'm-0 px-[14px] py-4 text-[13px] font-extrabold leading-[1.35]',

  authTrigger: 'cursor-pointer border-2 border-ink bg-transparent px-[13px] py-[10px] text-[11px] font-[950] tracking-[.07em] text-ink uppercase hover:bg-ink hover:text-paper',
  authLoading: 'block h-[37px] w-[74px] border-2 border-line',
  accountControl: 'relative flex items-center',
  accountMenuTrigger: 'flex max-w-[220px] cursor-pointer items-center gap-[9px] border-2 border-ink bg-transparent px-[13px] py-[10px] text-[11px] font-[950] tracking-[.07em] text-ink uppercase hover:bg-ink hover:text-paper aria-expanded:bg-ink aria-expanded:text-paper max-[780px]:max-w-32 max-[780px]:p-[9px] [&_span]:overflow-hidden [&_span]:text-ellipsis [&_span]:whitespace-nowrap [&_b]:text-[15px] [&_b]:leading-[.7] [&_b]:transition-transform [&_b]:duration-150 aria-expanded:[&_b]:rotate-180',
  accountMenu: 'absolute top-[calc(100%+9px)] right-0 z-10 w-[225px] border-2 border-ink bg-paper shadow-[6px_6px_0_var(--color-signal)] max-[780px]:w-[210px] [&>a]:flex [&>a]:min-h-11 [&>a]:w-full [&>a]:items-center [&>a]:border-0 [&>a]:border-b [&>a]:border-line [&>a]:bg-transparent [&>a]:px-[14px] [&>a]:text-left [&>a]:text-[10px] [&>a]:font-[950] [&>a]:tracking-[.08em] [&>a]:text-ink [&>a]:uppercase [&>a]:no-underline [&>a:hover]:bg-ink [&>a:hover]:text-paper [&>button]:flex [&>button]:min-h-11 [&>button]:w-full [&>button]:cursor-pointer [&>button]:items-center [&>button]:border-0 [&>button]:border-b [&>button]:border-line [&>button]:bg-transparent [&>button]:px-[14px] [&>button]:text-left [&>button]:text-[10px] [&>button]:font-[950] [&>button]:tracking-[.08em] [&>button]:text-ink [&>button]:uppercase [&>button:hover]:bg-ink [&>button:hover]:text-paper [&>button:last-child]:border-t-2 [&>button:last-child]:border-b-0 [&>button:last-child]:border-t-ink [&>button:last-child]:text-signal [&>button:last-child:hover]:bg-signal [&>button:last-child:hover]:text-white',
  accountMenuLiked: 'gap-[9px] [&_svg]:size-[15px] [&_svg]:fill-signal [&_svg]:stroke-current [&_svg]:stroke-[1.6] [&_svg]:[stroke-linejoin:round] hover:[&_svg]:fill-current',
  accountMenuComments: 'gap-[9px] [&_svg]:size-[15px] [&_svg]:fill-none [&_svg]:stroke-current [&_svg]:stroke-[1.8] [&_svg]:[stroke-linejoin:round]',
  authBackdrop: 'fixed inset-0 z-20 grid place-items-center bg-ink/72 p-5',
  authDialog: 'relative max-h-[calc(100vh-40px)] w-[min(100%,510px)] overflow-auto border-2 border-ink bg-paper p-[46px] shadow-[10px_10px_0_var(--color-signal)] max-[780px]:px-6 max-[780px]:pt-[42px] max-[780px]:pb-[30px] [&>h2]:m-0 [&>h2]:max-w-[420px] [&>h2]:text-[clamp(43px,6vw,68px)] [&>h2]:leading-[.86] [&>h2]:tracking-[-.065em] [&>h2]:uppercase [&>form]:grid [&>form]:gap-[17px] [&>form_label]:grid [&>form_label]:gap-[7px] [&>form_label]:text-[10px] [&>form_label]:font-[950] [&>form_label]:tracking-[.1em] [&>form_label]:uppercase [&>form_input]:w-full [&>form_input]:rounded-none [&>form_input]:border-[1.5px] [&>form_input]:border-ink [&>form_input]:bg-white [&>form_input]:px-[14px] [&>form_input]:py-[13px] [&>form_input]:font-sans [&>form_input]:text-[16px] [&>form_input]:font-semibold [&>form_input]:text-ink [&>form_input]:outline-none [&>form_input]:focus:shadow-[3px_3px_0_var(--color-signal)]',
  authClose: 'absolute top-[14px] right-[17px] cursor-pointer border-0 bg-transparent text-[34px] leading-none text-ink',
  authIntro: 'mt-6 mb-7 text-[15px] font-bold leading-[1.45]',
  authFieldHint: 'text-[10px] font-bold leading-[1.4] tracking-normal text-[#667085] normal-case',
  turnstileField: 'min-h-[65px] [&>div]:max-w-full [&_iframe]:max-w-full',
  authError: 'm-0 text-[13px] font-extrabold leading-[1.35] text-[#b51f2b]',
  authSubmit: 'flex min-h-[55px] cursor-pointer items-center justify-between border-0 bg-signal px-[18px] text-[12px] font-[950] tracking-[.09em] text-white shadow-[4px_4px_0_var(--color-ink)] disabled:cursor-wait disabled:opacity-65',
  authSwitch: 'mt-6 mb-0 text-[13px] font-bold [&_button]:cursor-pointer [&_button]:border-0 [&_button]:border-b [&_button]:border-current [&_button]:bg-transparent [&_button]:p-0 [&_button]:font-[950] [&_button]:text-ink',

  hero: 'grid min-h-[640px] grid-cols-[1.1fr_.9fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  heroCopy: `${diagonalInk} border-r-2 border-ink px-[6vw] pt-[85px] pb-[75px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[65px] max-[780px]:pb-[58px]`,
  heroCta: 'w-full max-w-[740px]',
  heroCtaImage: 'block h-auto w-full',
  dek: 'mt-[54px] mb-0 max-w-[570px] text-[clamp(18px,2vw,25px)] font-semibold leading-[1.35] max-[780px]:mt-[43px]',
  issueCard: 'flex flex-col justify-center bg-ink px-[6vw] pt-[88px] pb-[70px] text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[58px]',
  issueCardPrompt: 'mt-0 mb-8 max-w-[480px] text-[clamp(24px,2.5vw,36px)] font-black leading-[1.02] tracking-[-.05em]',
  issueOptions: 'grid grid-cols-2 gap-[11px] max-[780px]:grid-cols-1',
  issueOptionsLoading: 'w-full',
  issueOptionPlaceholder: "relative min-h-[62px] w-full overflow-hidden border-2 border-paper/42 bg-paper/14 shadow-[5px_5px_0_rgba(241,250,238,.1)] after:absolute after:inset-0 after:-translate-x-full after:animate-issue-shimmer after:bg-[linear-gradient(90deg,transparent,rgba(241,250,238,.28),transparent)] after:content-[''] motion-reduce:after:animate-none motion-reduce:after:translate-x-0",
  issueOption: 'flex min-h-[62px] w-full cursor-pointer items-center justify-start rounded-none border-2 border-paper bg-paper px-[14px] py-[13px] text-left text-ink shadow-[5px_5px_0_rgba(241,250,238,.28)] transition-[transform,box-shadow,background,color] duration-150 hover:translate-[3px] hover:border-signal hover:bg-signal hover:text-white hover:shadow-[2px_2px_0_var(--color-paper)] focus-visible:translate-[3px] focus-visible:border-signal focus-visible:bg-signal focus-visible:text-white focus-visible:shadow-[2px_2px_0_var(--color-paper)] focus-visible:outline-3 focus-visible:outline-offset-3 focus-visible:outline-paper disabled:cursor-not-allowed disabled:transform-none disabled:border-paper disabled:bg-paper disabled:text-ink disabled:opacity-[.58] disabled:shadow-none [&>span]:min-w-0 [&>span]:text-[15px] [&>span]:font-[950] [&>span]:leading-[1.08] [&>span]:tracking-normal [&>span]:uppercase [&>span]:[overflow-wrap:anywhere] max-[780px]:[&>span]:text-[17px]',
  issueOptionActive: 'translate-[3px] border-signal bg-signal text-white shadow-[2px_2px_0_var(--color-paper)]',
  microcopy: 'mt-[22px] mb-0 text-[12px] text-[#aeb7c7]',
  actionsSection: 'px-[5vw] pt-[85px] pb-[105px] max-[780px]:px-5 max-[780px]:pt-[65px] max-[780px]:pb-[75px]',
  sectionHeading: 'mb-[55px] grid grid-cols-[1fr_.7fr] items-end gap-10 max-[780px]:mb-[38px] max-[780px]:grid-cols-1 [&_h2]:m-0 [&_h2]:text-[clamp(46px,6vw,85px)] [&_h2]:leading-[.86] [&_h2]:tracking-[-.07em] [&_h2]:uppercase [&>p]:m-0 [&>p]:max-w-[510px] [&>p]:text-[16px] [&>p]:font-semibold [&>p]:leading-[1.55]',
  homepageIssueHeading: 'inline-block',
  issuePageActionHeading: 'inline-block',
  issueHeadingLink: 'text-inherit decoration-signal decoration-4 underline-offset-8 hover:text-signal focus-visible:outline-3 focus-visible:outline-offset-8 focus-visible:outline-signal',
  filterRow: 'flex flex-wrap gap-[9px] border-b-2 border-ink pb-[17px] [&_button]:cursor-pointer [&_button]:border-[1.5px] [&_button]:border-ink [&_button]:bg-transparent [&_button]:px-[15px] [&_button]:py-[10px] [&_button]:text-[12px] [&_button]:font-black [&_button]:tracking-[.06em] [&_button]:text-ink [&_button]:uppercase [&_button:hover]:bg-ink [&_button:hover]:text-paper [&_sup]:pl-0.5 [&_sup]:text-signal',
  filterActive: 'bg-ink! text-paper!',
  actionCard: 'grid grid-cols-[minmax(0,1fr)_160px] items-start gap-6 border-b-[1.5px] border-ink px-1 py-8 max-[780px]:grid-cols-1 max-[780px]:gap-4',
  emptyState: 'm-0 border-b-[1.5px] border-ink px-1 py-[42px] text-[18px] font-extrabold',
  homepageBrowseMore: '!mt-[38px] w-[min(100%,360px)] !shadow-[5px_5px_0_var(--color-ink)] hover:!shadow-[2px_2px_0_var(--color-ink)]',
  cardMain: '[&_h3]:m-0 [&_h3]:text-[clamp(20px,1.8vw,29px)] [&_h3]:leading-[1.08] [&_h3]:tracking-[-.035em] [&_h3_a]:decoration-[1.5px] [&_h3_a]:underline-offset-[5px] [&_h3_a:hover]:text-signal [&>p]:my-[13px] [&>p]:max-w-[720px] [&>p]:text-[15px] [&>p]:leading-[1.5]',
  actionTitleRow: 'flex items-start gap-3',
  likeButton: 'mt-0 size-[31px] flex-none cursor-pointer border-0 bg-transparent p-0.5 text-ink focus-visible:outline-3 focus-visible:outline-offset-3 focus-visible:outline-signal disabled:cursor-wait disabled:opacity-55 [&_svg]:block [&_svg]:size-full [&_svg]:fill-transparent [&_svg]:stroke-current [&_svg]:stroke-[1.8] [&_svg]:transition-[fill,color,transform] [&_svg]:duration-150 [&_svg]:[stroke-linejoin:round] hover:[&_svg]:scale-[1.08] hover:[&_svg]:text-signal',
  likeButtonLiked: 'text-signal [&_svg]:fill-current',
  likeError: 'mt-[18px] mb-0 text-[13px] font-extrabold text-[#b51f2b]',
  organization: 'flex flex-wrap items-center gap-[5px] text-[9px] font-black leading-4 tracking-[.08em] [&>a]:inline-flex [&>a]:min-h-4 [&>a]:items-center [&>a]:leading-4 [&>a]:underline-offset-3 [&>a:hover]:text-signal',
  organizationPrefix: 'inline-flex min-h-4 items-center leading-4',
  organizationSeparator: 'inline-flex min-h-4 items-center leading-4',
  organizationInlineLink: 'underline-offset-3 hover:text-signal',
  typePill: 'inline-flex min-h-4 items-center rounded-full border border-ink bg-ink px-1.5 leading-4 tracking-[.05em] text-paper normal-case',
  typePillUrgent: '!border-signal !bg-signal !text-white uppercase',
  cardAction: 'flex self-start flex-col items-end gap-[10px] max-[780px]:items-start [&>span]:text-[10px] [&>span]:font-black [&>span]:text-[#60697d] [&>span]:uppercase [&>a]:flex [&>a]:min-h-[42px] [&>a]:w-[150px] [&>a]:items-center [&>a]:justify-center [&>a]:bg-signal [&>a]:px-4 [&>a]:text-[11px] [&>a]:font-[950] [&>a]:tracking-[.09em] [&>a]:text-white [&>a]:uppercase [&>a]:no-underline [&>a]:shadow-[4px_4px_0_var(--color-ink)] [&>a]:transition-[transform,box-shadow] [&>a]:duration-150 [&>a:hover]:translate-[2px] [&>a:hover]:shadow-[2px_2px_0_var(--color-ink)] max-[780px]:[&>a]:w-full',
  trustBand: 'grid grid-cols-[140px_1fr_.8fr] items-center gap-[50px] bg-signal px-[7vw] py-20 text-white max-[780px]:grid-cols-1 max-[780px]:gap-[30px] max-[780px]:px-5 max-[780px]:py-[65px] [&_h2]:m-0 [&_h2]:text-[clamp(46px,6vw,85px)] [&_h2]:leading-[.86] [&_h2]:tracking-[-.07em] [&_h2]:uppercase [&>p]:max-w-[490px] [&>p]:font-bold [&>p]:leading-[1.55]',
  trustMark: 'grid size-[120px] -rotate-8 place-items-center rounded-full border-4 border-paper max-[780px]:size-[82px] [&>span]:text-[65px] [&>span]:font-black max-[780px]:[&>span]:text-[44px]',

  footer: 'grid min-h-[180px] grid-cols-3 items-center gap-[30px] border-t-2 border-ink bg-[#13203C] px-[5vw] py-[45px] text-white max-[780px]:grid-cols-1 max-[780px]:justify-items-center max-[780px]:text-center [&>p]:text-center [&>p]:font-extrabold max-[780px]:[&>p]:py-1 [&>div]:flex [&>div]:flex-wrap [&>div]:justify-end [&>div]:gap-x-[22px] [&>div]:gap-y-[14px] [&>div]:text-[11px] [&>div]:font-black [&>div]:uppercase max-[780px]:[&>div]:flex-col max-[780px]:[&>div]:items-center max-[780px]:[&>div]:justify-start',
  footerBrand: 'max-[780px]:w-full max-[780px]:justify-center max-[780px]:justify-self-center [&_img]:block [&_img]:h-auto [&_img]:w-[min(100%,285px)]',
  footerSticker: 'mx-auto mt-4 block h-auto w-[153px] max-w-full max-[780px]:mt-0',

  apiHero: 'grid min-h-[560px] grid-cols-[1.15fr_.85fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  apiHeroHeading: `${diagonalInk} border-r-2 border-ink px-[6vw] pt-[68px] pb-[72px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  apiBackLink: 'mb-[54px] inline-block text-[11px] font-[950] tracking-[.07em] uppercase underline-offset-[5px] max-[780px]:mb-12',
  apiTitle: `${headingBase} text-[clamp(61px,8vw,118px)] max-[780px]:text-[clamp(54px,18vw,84px)]`,
  apiHeroCopy: 'mt-12 mb-0 max-w-[650px] text-[clamp(17px,2vw,23px)] font-[650] leading-[1.45] max-[780px]:mt-10',
  apiHeroAside: 'flex flex-col justify-center bg-ink px-[6vw] py-[70px] text-paper max-[780px]:px-5 max-[780px]:pt-[52px] max-[780px]:pb-[60px] [&>strong]:mt-6 [&>strong]:text-[clamp(36px,5vw,64px)] [&>strong]:leading-[.85] [&>strong]:tracking-[-.06em] [&>strong]:text-signal [&>span]:mt-[9px] [&>span]:max-w-[390px] [&>span]:text-[15px] [&>span]:font-bold [&>span]:leading-[1.45] [&>span]:text-[#cbd2df]',
  apiDocs: 'bg-paper',
  apiSection: 'grid grid-cols-[minmax(240px,.72fr)_minmax(0,1.28fr)] border-b-2 border-ink max-[780px]:grid-cols-1',
  apiSectionHeading: 'border-r-2 border-ink px-[5vw] py-20 max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[42px] [&_h2]:m-0 [&_h2]:text-[clamp(45px,6vw,82px)] [&_h2]:leading-[.87] [&_h2]:tracking-[-.07em] [&_h2]:uppercase [&_h2_code]:font-[inherit] [&_h2_code]:text-signal',
  apiSectionHeadingSource: 'bg-signal text-white',
  apiSectionContent: 'min-w-0 px-[6vw] pt-20 pb-[90px] max-[780px]:px-5 max-[780px]:pt-[50px] max-[780px]:pb-[65px] [&>p]:mt-0 [&>p]:mb-[30px] [&>p]:max-w-[780px] [&>p]:text-[17px] [&>p]:font-[650] [&>p]:leading-[1.65] [&_h3]:mt-12 [&_h3]:mb-[17px] [&_h3]:text-[22px] [&_h3]:tracking-[-.035em] [&_h3]:uppercase [&_code]:font-mono [&_code]:font-extrabold [&_pre]:mb-[25px] [&_pre]:mt-0 [&_pre]:max-w-full [&_pre]:overflow-auto [&_pre]:border-l-[6px] [&_pre]:border-signal [&_pre]:bg-ink [&_pre]:p-[22px] [&_pre]:font-mono [&_pre]:text-[13px] [&_pre]:font-bold [&_pre]:leading-[1.65] [&_pre]:text-paper',
  apiEndpointList: 'mt-10 border-t-2 border-ink',
  apiEndpoint: 'grid grid-cols-[60px_minmax(0,1fr)] gap-5 border-b-[1.5px] border-ink py-6 max-[780px]:grid-cols-[52px_minmax(0,1fr)] max-[780px]:gap-[13px] [&>span]:self-start [&>span]:bg-signal [&>span]:px-[7px] [&>span]:py-1.5 [&>span]:text-center [&>span]:text-[9px] [&>span]:font-[950] [&>span]:tracking-[.08em] [&>span]:text-white [&_code]:text-[15px] [&_code]:[overflow-wrap:anywhere] [&_p]:mt-2 [&_p]:mb-0 [&_p]:text-[14px] [&_p]:font-[650] [&_p]:leading-[1.45] [&_p]:text-[#48536a]',
  apiMcpSection: 'bg-[#e1eadf]',
  apiMcpAddress: 'mt-[38px] grid gap-2 border-2 border-ink bg-paper p-[25px] shadow-[6px_6px_0_var(--color-signal)] [&_small]:mt-[10px] [&_small]:text-[9px] [&_small]:font-[950] [&_small]:tracking-[.1em] [&_small]:text-[#667085] [&_small:first-child]:mt-0 [&_code]:text-[14px] [&_code]:[overflow-wrap:anywhere]',
  apiNote: 'border-l-4 border-signal pl-4 !text-[14px] text-[#48536a]',
  apiToolList: 'border-t-2 border-ink [&>div]:grid [&>div]:grid-cols-[minmax(155px,.45fr)_minmax(0,1fr)] [&>div]:gap-[25px] [&>div]:border-b-[1.5px] [&>div]:border-ink [&>div]:py-5 max-[780px]:[&>div]:grid-cols-1 max-[780px]:[&>div]:gap-2 [&_code]:text-[14px] [&_code]:text-[#b51f2b] [&_code]:[overflow-wrap:anywhere] [&_p]:m-0 [&_p]:text-[14px] [&_p]:font-[650] [&_p]:leading-[1.5]',
  apiSourceLink: 'mt-[38px] flex min-h-16 items-center justify-between gap-[25px] border-2 border-ink bg-ink px-5 text-[12px] font-[950] tracking-[.09em] text-paper no-underline shadow-[5px_5px_0_var(--color-signal)] hover:translate-[3px] hover:border-signal hover:bg-signal hover:shadow-[2px_2px_0_var(--color-ink)] [&_b]:text-[18px]',
  apiSetupSteps: "m-0 list-none p-0 [counter-reset:api-step] [&>li]:relative [&>li]:border-t-[1.5px] [&>li]:border-ink [&>li]:pt-6 [&>li]:pr-0 [&>li]:pb-[26px] [&>li]:pl-[58px] [&>li]:[counter-increment:api-step] [&>li:last-child]:border-b-[1.5px] [&>li]:before:absolute [&>li]:before:top-6 [&>li]:before:left-0 [&>li]:before:font-sans [&>li]:before:text-[13px] [&>li]:before:font-[950] [&>li]:before:text-signal [&>li]:before:content-[counter(api-step,decimal-leading-zero)] [&_strong]:mb-[9px] [&_strong]:block [&_strong]:text-[16px] [&_strong]:uppercase [&_p]:mt-0 [&_p]:mb-[14px] [&_p]:max-w-[760px] [&_p]:text-[14px] [&_p]:font-[650] [&_p]:leading-[1.55] [&_p]:text-[#48536a] [&_pre]:mt-[14px] [&_pre]:mb-0 [&_a]:font-black [&_a]:text-[#b51f2b] [&_a]:underline-offset-4",

  submissionShell: 'grid min-h-[calc(100vh-78px)] grid-cols-[.85fr_1.15fr] max-[780px]:grid-cols-1',
  submissionHeading: `${diagonalInk} border-r-2 border-ink px-[5vw] py-20 max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:py-[58px]`,
  submissionTitle: `${headingBase} text-[clamp(60px,7vw,108px)] max-[780px]:text-[clamp(58px,20vw,92px)]`,
  submissionHeadingCopy: 'mt-[45px] mb-7 max-w-[470px] text-[17px] font-bold leading-[1.5]',
  submissionHeadingLink: 'text-[11px] font-[950] tracking-[.07em] uppercase underline-offset-[5px]',
  submissionPanel: 'flex items-start justify-center bg-ink px-[5vw] py-20 text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[70px]',
  submissionForm: 'grid w-[min(100%,650px)] gap-5 [&_h2]:m-0 [&_h2]:text-[clamp(42px,5vw,68px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&_label]:grid [&_label]:gap-2 [&_label]:text-[10px] [&_label]:font-[950] [&_label]:tracking-[.1em] [&_label]:text-paper [&_label]:uppercase [&_label_small]:text-[10px] [&_label_small]:font-bold [&_label_small]:tracking-normal [&_label_small]:text-[#aeb7c7] [&_label_small]:normal-case [&_input]:w-full [&_input]:rounded-none [&_input]:border-2 [&_input]:border-transparent [&_input]:bg-paper [&_input]:px-[15px] [&_input]:py-[14px] [&_input]:font-sans [&_input]:text-[16px] [&_input]:font-bold [&_input]:leading-[1.35] [&_input]:text-ink [&_input]:outline-none [&_input]:focus:border-signal [&_input]:focus:shadow-[4px_4px_0_var(--color-signal)] [&_input[readonly]]:cursor-default [&_input[readonly]]:bg-[#dfe8dd] [&_input[readonly]]:text-[#667085] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-none [&_textarea]:border-2 [&_textarea]:border-transparent [&_textarea]:bg-paper [&_textarea]:px-[15px] [&_textarea]:py-[14px] [&_textarea]:font-sans [&_textarea]:text-[16px] [&_textarea]:font-bold [&_textarea]:leading-[1.35] [&_textarea]:text-ink [&_textarea]:outline-none [&_textarea]:focus:border-signal [&_textarea]:focus:shadow-[4px_4px_0_var(--color-signal)] [&_select]:w-full [&_select]:resize-y [&_select]:rounded-none [&_select]:border-2 [&_select]:border-transparent [&_select]:bg-paper [&_select]:px-[15px] [&_select]:py-[14px] [&_select]:font-sans [&_select]:text-[16px] [&_select]:font-bold [&_select]:leading-[1.35] [&_select]:text-ink [&_select]:outline-none [&_select]:focus:border-signal [&_select]:focus:shadow-[4px_4px_0_var(--color-signal)]',
  submissionStatus: 'w-[min(100%,650px)] [&_h2]:m-0 [&_h2]:text-[clamp(42px,5vw,68px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&>p:not(:first-child)]:mt-6 [&>p:not(:first-child)]:mb-[30px] [&>p:not(:first-child)]:text-[15px] [&>p:not(:first-child)]:font-[650] [&>p:not(:first-child)]:leading-[1.5] [&>p:not(:first-child)]:text-[#cbd2df] [&>button]:border-paper [&>button]:text-paper [&>button:hover]:bg-paper [&>button:hover]:text-ink',
  formIntro: 'mt-6 mb-[30px] text-[15px] font-[650] leading-[1.5] text-[#cbd2df]',
  submissionStatusCopy: 'mt-6 mb-[30px] text-[15px] font-[650] leading-[1.5] text-[#cbd2df]',
  successFormSubmit: '!mt-1.5',
  formGrid: 'grid grid-cols-2 gap-[18px] max-[780px]:grid-cols-1',
  formTitleRow: 'flex items-end justify-between gap-5 max-[780px]:flex-col max-[780px]:items-start [&_button]:cursor-pointer [&_button]:whitespace-nowrap [&_button]:border-0 [&_button]:border-b [&_button]:border-current [&_button]:bg-transparent [&_button]:px-0 [&_button]:pb-[3px] [&_button]:text-[10px] [&_button]:font-[950] [&_button]:tracking-[.07em] [&_button]:text-paper [&_button]:uppercase',
  successActions: 'grid items-center gap-6 [&>button]:justify-self-start [&>button]:cursor-pointer [&>button]:whitespace-nowrap [&>button]:border-0 [&>button]:border-b [&>button]:border-current [&>button]:bg-transparent [&>button]:px-0 [&>button]:pb-[3px] [&>button]:text-[10px] [&>button]:font-[950] [&>button]:tracking-[.07em] [&>button]:text-paper [&>button]:uppercase',

  adminShell: 'grid min-h-[calc(100vh-78px)] grid-cols-[.72fr_1.28fr] max-[780px]:grid-cols-1',
  adminHeading: 'sticky top-0 min-h-[calc(100vh-78px)] self-start border-r-2 border-ink bg-signal px-[5vw] py-[78px] text-white max-[780px]:static max-[780px]:min-h-0 max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:py-[58px]',
  adminTitle: `${headingBase} text-[clamp(60px,7vw,108px)] max-[780px]:text-[clamp(58px,20vw,92px)]`,
  adminHeadingCopy: 'mt-[45px] mb-7 max-w-[470px] text-[17px] font-bold leading-[1.5]',
  reviewList: 'px-[5vw] pt-[50px] pb-[90px] max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[70px]',
  adminMessage: 'm-0 py-[30px] text-[17px] font-extrabold',
  reviewCard: 'border-b-2 border-ink pt-[34px] pb-[38px] first:pt-0 [&_h2]:m-0 [&_h2]:text-[clamp(28px,3vw,45px)] [&_h2]:leading-none [&_h2]:tracking-[-.045em] [&>p]:mt-4 [&>p]:mb-[22px] [&>p]:max-w-[760px] [&>p]:text-[15px] [&>p]:font-[650] [&>p]:leading-[1.5] [&_dl]:mb-[25px] [&_dl]:mt-0 [&_dl]:flex [&_dl]:flex-wrap [&_dl]:gap-x-[50px] [&_dl]:gap-y-[25px] [&_dl_div]:grid [&_dl_div]:gap-1 [&_dt]:text-[9px] [&_dt]:font-[950] [&_dt]:tracking-[.08em] [&_dt]:uppercase [&_dd]:m-0 [&_dd]:text-[13px] [&_dd]:font-bold',
  reviewMeta: 'mb-[15px] flex flex-wrap gap-[7px] [&_span]:border [&_span]:border-ink [&_span]:px-[7px] [&_span]:py-[5px] [&_span]:text-[9px] [&_span]:font-[950] [&_span]:tracking-[.09em] [&_span]:uppercase',
  reviewDescription: '-mt-1 mb-6 border-l-4 border-signal py-2 pl-[14px] [&_summary]:cursor-pointer [&_summary]:text-[10px] [&_summary]:font-[950] [&_summary]:tracking-[.08em] [&_summary]:uppercase [&_pre]:mt-[15px] [&_pre]:mb-0 [&_pre]:max-h-[280px] [&_pre]:overflow-auto [&_pre]:whitespace-pre-wrap [&_pre]:bg-white [&_pre]:p-[15px] [&_pre]:font-mono [&_pre]:text-[13px] [&_pre]:font-semibold [&_pre]:leading-[1.5]',
  reviewActions: 'flex items-center justify-between gap-5 max-[780px]:flex-col max-[780px]:items-start [&_a]:text-[11px] [&_a]:font-[950] [&_a]:tracking-[.06em] [&_a]:uppercase [&_a]:underline-offset-[5px] [&_button]:min-h-[46px] [&_button]:cursor-pointer [&_button]:border-0 [&_button]:bg-ink [&_button]:px-4 [&_button]:text-[10px] [&_button]:font-[950] [&_button]:tracking-[.08em] [&_button]:text-paper [&_button:hover]:bg-signal [&_button:disabled]:cursor-wait [&_button:disabled]:opacity-60',

  settingsShell: 'grid min-h-[calc(100vh-78px)] grid-cols-[.78fr_1.22fr] max-[780px]:grid-cols-1',
  settingsHeading: `${diagonalInk} border-r-2 border-ink px-[5vw] py-20 max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:py-[58px]`,
  settingsTitle: `${headingBase} text-[clamp(60px,7vw,108px)] max-[780px]:text-[clamp(58px,20vw,92px)]`,
  settingsHeadingCopy: 'mt-[45px] mb-7 max-w-[430px] text-[17px] font-bold leading-[1.5]',
  settingsHeadingLink: 'text-[11px] font-[950] tracking-[.07em] uppercase underline-offset-[5px]',
  settingsPanel: 'bg-ink px-[5vw] pt-[65px] pb-[90px] text-paper max-[780px]:px-5 max-[780px]:pt-[50px] max-[780px]:pb-[75px]',
  settingsStack: 'mx-auto grid w-[min(100%,720px)] gap-[34px]',
  settingsForm: 'mx-auto grid w-[min(100%,720px)] gap-[18px] border-2 border-paper bg-paper p-[34px] text-ink shadow-[7px_7px_0_var(--color-signal)] max-[780px]:px-5 max-[780px]:py-[27px] [&_h2]:m-0 [&_h2]:text-[clamp(31px,4vw,48px)] [&_h2]:leading-[.95] [&_h2]:tracking-[-.05em] [&_h2]:uppercase [&_label]:grid [&_label]:gap-2 [&_label]:text-[10px] [&_label]:font-[950] [&_label]:tracking-[.1em] [&_label]:uppercase [&_label_small]:text-[10px] [&_label_small]:font-bold [&_label_small]:tracking-normal [&_label_small]:text-[#667085] [&_label_small]:normal-case [&_input]:w-full [&_input]:rounded-none [&_input]:border-[1.5px] [&_input]:border-ink [&_input]:bg-white [&_input]:px-[14px] [&_input]:py-[13px] [&_input]:font-sans [&_input]:text-[16px] [&_input]:font-bold [&_input]:leading-[1.45] [&_input]:text-ink [&_input]:outline-none [&_input]:focus:shadow-[3px_3px_0_var(--color-signal)] [&_input[readonly]]:bg-[#e4ebe2] [&_input[readonly]]:text-[#667085] [&_textarea]:min-h-[220px] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-none [&_textarea]:border-[1.5px] [&_textarea]:border-ink [&_textarea]:bg-white [&_textarea]:px-[14px] [&_textarea]:py-[13px] [&_textarea]:font-sans [&_textarea]:text-[16px] [&_textarea]:font-bold [&_textarea]:leading-[1.45] [&_textarea]:text-ink [&_textarea]:outline-none [&_textarea]:focus:shadow-[3px_3px_0_var(--color-signal)]',
  settingsSubmit: 'flex min-h-[54px] cursor-pointer items-center justify-between border-0 bg-signal px-[17px] text-[11px] font-[950] tracking-[.09em] text-white shadow-[4px_4px_0_var(--color-ink)] disabled:cursor-wait disabled:opacity-[.62]',
  settingsMessage: 'mx-auto w-[min(100%,650px)] text-[16px] font-bold leading-[1.5] text-paper [&_h2]:m-0 [&_h2]:text-[clamp(31px,4vw,48px)] [&_h2]:leading-[.95] [&_h2]:tracking-[-.05em] [&_h2]:uppercase [&_p]:mt-5 [&_p]:mb-[25px] [&_p]:text-[#cbd2df] [&>button]:border-paper [&>button]:text-paper [&>button:hover]:bg-paper [&>button:hover]:text-ink',
  settingsIntro: 'm-0 text-[14px] font-bold leading-[1.5] text-[#48536a]',
  settingsBlockList: 'm-0 grid list-none gap-3 p-0 [&_li]:grid [&_li]:grid-cols-[44px_minmax(0,1fr)_auto] [&_li]:items-center [&_li]:gap-3 [&_li]:border-t [&_li]:border-[#cdd5ca] [&_li]:pt-3 [&_button]:cursor-pointer [&_button]:border-0 [&_button]:bg-transparent [&_button]:p-1 [&_button]:text-[10px] [&_button]:font-[950] [&_button]:tracking-[.08em] [&_button]:text-signal [&_button:disabled]:cursor-wait [&_button:disabled]:opacity-55',
  settingsBlockAvatar: 'relative grid size-11 place-items-center overflow-hidden rounded-full border-2 border-ink bg-[#dfe8dd] text-[12px] font-[950] [&_img]:absolute [&_img]:inset-0 [&_img]:size-full [&_img]:object-cover',
  settingsBlockIdentity: 'flex min-w-0 flex-col [&_strong]:truncate [&_strong]:text-[14px] [&_small]:mt-0.5 [&_small]:text-[11px] [&_small]:font-extrabold [&_small]:text-[#667085]',
  avatarSettingsRow: 'grid grid-cols-[100px_minmax(0,1fr)] items-center gap-[22px] max-[780px]:grid-cols-[76px_minmax(0,1fr)] max-[780px]:gap-[15px] [&>div>small]:mt-[9px] [&>div>small]:block [&>div>small]:text-[11px] [&>div>small]:font-bold [&>div>small]:leading-[1.4] [&>div>small]:text-[#667085]',
  accountAvatarPreview: 'relative grid size-[100px] place-items-center overflow-hidden rounded-full border-2 border-ink bg-[#dfe8dd] text-[28px] font-[950] text-ink max-[780px]:size-[76px] max-[780px]:text-[22px] [&_img]:absolute [&_img]:inset-0 [&_img]:size-full [&_img]:object-cover',
  avatarFileLabel: 'inline-flex! min-h-[42px] w-max max-w-full cursor-pointer items-center border-[1.5px] border-ink px-[13px] hover:bg-ink hover:text-paper [&_input]:absolute [&_input]:h-px [&_input]:w-px [&_input]:overflow-hidden [&_input]:whitespace-nowrap [&_input]:[clip-path:inset(50%)] [&_input]:[clip:rect(0_0_0_0)]',
  avatarSettingsActions: 'flex flex-wrap items-center gap-4 [&>button:first-child]:basis-[230px] [&>button:first-child]:grow',
  avatarRemove: 'cursor-pointer border-0 border-b border-current bg-transparent px-0 py-1 text-[10px] font-[950] tracking-[.08em] text-[#a81522] uppercase disabled:cursor-wait disabled:opacity-55',
  organizationForm: 'mt-[18px]',
  organizationActionList: 'mt-[45px] mb-[30px] border-t-2 border-ink',
  organizationActionListLabel: 'm-0 border-b border-line px-0 pt-4 pb-[13px] text-[#667085]',
  organizationActionRow: 'grid grid-cols-[28px_minmax(0,1fr)_20px] items-start gap-[10px] border-b-[1.5px] border-ink py-[18px] no-underline hover:[&_strong]:text-signal focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-signal focus-visible:[&_strong]:text-signal',
  organizationActionNumber: 'pt-[3px] text-[10px] font-[950] text-signal',
  organizationActionCopy: 'grid min-w-0 gap-[7px] [&_strong]:text-[18px] [&_strong]:leading-[1.05] [&_strong]:tracking-[-.03em] [&_strong]:transition-colors [&_strong]:duration-150 [&_small]:line-clamp-2 [&_small]:overflow-hidden [&_small]:text-[11px] [&_small]:font-bold [&_small]:leading-[1.35] [&_small]:text-[#48536a]',
  organizationActionMeta: 'flex flex-wrap items-center gap-[7px] [&_b]:border [&_b]:border-ink [&_b]:px-[5px] [&_b]:py-1 [&_b]:text-[8px] [&_b]:font-[950] [&_b]:tracking-[.08em] [&_b]:uppercase [&_i]:text-[8px] [&_i]:font-[950] [&_i]:not-italic [&_i]:tracking-[.08em] [&_i]:text-[#667085] [&_i]:uppercase',
  organizationActionArrow: 'self-center text-[18px] font-black',
  organizationActionsEmpty: 'm-0 border-b-[1.5px] border-ink py-5 text-[13px] font-extrabold text-[#667085]',
  secondaryLink: 'mt-[5px] justify-self-start text-[10px] font-[950] tracking-[.08em] uppercase underline-offset-[5px]',

  actionDetailHero: 'grid grid-cols-[1.35fr_.65fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  actionDetailHeading: `${diagonalInk} min-w-0 border-r-2 border-ink px-[6vw] pt-[65px] pb-[75px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  breadcrumb: "mb-[65px] text-[10px] font-[950] tracking-[.08em] uppercase max-[780px]:mb-12 [&_ol]:m-0 [&_ol]:flex [&_ol]:list-none [&_ol]:flex-wrap [&_ol]:items-center [&_ol]:p-0 [&_li]:flex [&_li]:min-w-0 [&_li]:items-center [&_li+li]:before:mx-[10px] [&_li+li]:before:text-[16px] [&_li+li]:before:font-bold [&_li+li]:before:leading-none [&_li+li]:before:text-signal [&_li+li]:before:content-['›'] [&_a]:border-b [&_a]:border-current [&_a]:no-underline [&_a:hover]:text-signal [&_[aria-current='page']]:max-w-[min(440px,40vw)] [&_[aria-current='page']]:text-[#667085] [&_[aria-current='page']_span]:overflow-hidden [&_[aria-current='page']_span]:text-ellipsis [&_[aria-current='page']_span]:whitespace-nowrap",
  actionDetailTitle: `${headingBase} max-w-[1050px] text-[clamp(55px,7.6vw,116px)] [overflow-wrap:anywhere] max-[780px]:text-[clamp(48px,15vw,75px)]`,
  actionDetailTitleEnding: 'inline-flex items-center whitespace-nowrap align-baseline',
  actionDetailTitleStar: 'ml-[.12em] block size-[.74em] object-contain',
  actionDetailBadges: 'mb-5 flex flex-wrap items-center gap-[10px]',
  actionDetailPillRow: 'inline-flex flex-wrap items-center gap-2 [&>span]:min-h-[31px] [&>span]:px-3 [&>span]:text-[11px] [&>span]:leading-[31px] [&>span]:tracking-[.08em] [&>span]:uppercase',
  actionDetailLike: 'contents',
  actionDetailLikeError: 'basis-full !mt-2',
  actionDetailSummary: 'mt-[42px] mb-[22px] max-w-[820px] text-[clamp(18px,2vw,25px)] font-[650] leading-[1.4]',
  actionDetailCta: 'flex flex-col justify-center bg-ink px-[5vw] py-[70px] text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[62px] [&_h2]:m-0 [&_h2]:text-[clamp(48px,5.5vw,80px)] [&_h2]:leading-[.85] [&_h2]:tracking-[-.07em] [&_h2]:uppercase [&>p:not(:first-child)]:mt-7 [&>p:not(:first-child)]:mb-2 [&>p:not(:first-child)]:text-[15px] [&>p:not(:first-child)]:font-bold [&>p:not(:first-child)]:leading-[1.5] [&>p:not(:first-child)]:text-[#cbd2df] [&>small]:mt-[22px] [&>small]:text-[10px] [&>small]:font-[950] [&>small]:tracking-[.09em] [&>small]:text-[#aeb7c7] [&>small]:uppercase',
  actionOpenGraphPreview: 'group block overflow-hidden border-2 border-paper/35 bg-[#253450] text-paper no-underline shadow-[6px_6px_0_rgba(241,250,238,.14)] transition-[transform,box-shadow] duration-150 hover:translate-[2px] hover:shadow-[3px_3px_0_rgba(241,250,238,.14)] focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-signal',
  actionOpenGraphImage: 'block aspect-[1.91/1] w-full bg-[#17233c] object-cover',
  actionOpenGraphBody: 'grid gap-[7px] px-4 py-[15px]',
  actionOpenGraphSite: 'overflow-hidden text-ellipsis whitespace-nowrap text-[9px] font-black tracking-[.1em] text-[#b9c2d2] uppercase',
  actionOpenGraphTitle: 'text-[17px] font-[900] leading-[1.15] tracking-[-.02em] text-paper group-hover:text-white',
  actionOpenGraphDescription: 'line-clamp-4 text-[12px] font-semibold leading-[1.4] text-[#d4d9e3]',
  actionOpenGraphUrl: 'overflow-hidden text-ellipsis whitespace-nowrap text-[10px] font-bold text-[#aeb7c7]',
  actionDescriptionShell: 'grid grid-cols-[minmax(220px,.55fr)_minmax(0,1.45fr)] gap-[8vw] px-[6vw] pt-[85px] pb-[115px] max-[780px]:grid-cols-1 max-[780px]:gap-[38px] max-[780px]:px-5 max-[780px]:pt-[65px] max-[780px]:pb-20',
  descriptionContent: 'min-w-0 max-w-[850px]',
  actionDetailsList: 'm-0 grid list-none gap-[18px] p-0 [&_li]:min-w-0 [&_li]:border-b-[1.5px] [&_li]:border-ink [&_li]:pb-[18px] [&_small]:mb-1.5 [&_small]:block [&_small]:text-[9px] [&_small]:font-[950] [&_small]:tracking-[.1em] [&_small]:text-[#667085] [&_small]:uppercase [&_div]:text-[14px] [&_div]:font-black [&_div]:leading-[1.25] [&_div]:[overflow-wrap:anywhere] [&_a]:decoration-[1.5px] [&_a]:underline-offset-4 [&_a:hover]:text-signal [&_p]:mt-1.5 [&_p]:mb-0 [&_p]:text-[12px] [&_p]:font-bold [&_p]:leading-[1.4] [&_p]:text-[#667085]',
  actionDetailsUrl: 'block max-w-full overflow-hidden text-ellipsis whitespace-nowrap',
  markdownContent: 'min-w-0 max-w-[850px] text-[17px] font-[550] leading-[1.7] [&>*:first-child]:mt-0 [&>*:last-child]:mb-0 [&_h1]:mt-[1.45em] [&_h1]:mb-[.55em] [&_h1]:text-[clamp(38px,5vw,62px)] [&_h1]:leading-none [&_h1]:tracking-[-.045em] [&_h1]:uppercase [&_h2]:mt-[1.45em] [&_h2]:mb-[.55em] [&_h2]:text-[clamp(31px,4vw,48px)] [&_h2]:leading-none [&_h2]:tracking-[-.045em] [&_h2]:uppercase [&_h3]:mt-[1.45em] [&_h3]:mb-[.55em] [&_h3]:text-[clamp(23px,3vw,32px)] [&_h3]:leading-none [&_h3]:tracking-[-.045em] [&_h3]:uppercase [&_p]:mt-0 [&_p]:mb-[1.25em] [&_ul]:mt-0 [&_ul]:mb-[1.25em] [&_ol]:mt-0 [&_ol]:mb-[1.25em] [&_blockquote]:mb-[1.25em] [&_li+li]:mt-[.45em] [&_a]:font-extrabold [&_a]:text-[#b51f2b] [&_a]:underline-offset-4 [&_blockquote]:ml-0 [&_blockquote]:border-l-[5px] [&_blockquote]:border-signal [&_blockquote]:py-[3px] [&_blockquote]:pl-5 [&_blockquote]:text-[1.1em] [&_blockquote]:font-bold [&_code]:bg-[#dfe8dd] [&_code]:px-[5px] [&_code]:py-0.5 [&_code]:text-[.9em] [&_pre]:max-w-full [&_pre]:overflow-auto [&_pre]:bg-ink [&_pre]:p-[18px] [&_pre]:text-paper [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_table]:block [&_table]:max-w-full [&_table]:border-collapse [&_table]:overflow-x-auto [&_th]:border [&_th]:border-ink [&_th]:bg-ink [&_th]:px-3 [&_th]:py-[10px] [&_th]:text-left [&_th]:text-paper [&_td]:border [&_td]:border-ink [&_td]:px-3 [&_td]:py-[10px] [&_td]:text-left [&_img]:h-auto [&_img]:max-w-full',
  actionDescriptionButton: '!mt-[38px] max-w-[360px] !text-white no-underline !shadow-[5px_5px_0_var(--color-ink)] hover:!text-white hover:!shadow-[2px_2px_0_var(--color-ink)]',

  actionCommentsShell: 'grid grid-cols-[minmax(260px,.55fr)_minmax(0,1.45fr)] border-t-2 border-ink bg-ink text-paper max-[780px]:grid-cols-1',
  actionCommentsHeading: `${diagonalPaper} border-r-2 border-paper px-[5vw] pt-[85px] pb-[100px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[58px] [&_h2]:m-0 [&_h2]:text-[clamp(43px,5vw,76px)] [&_h2]:leading-[.88] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&>p:last-child]:mt-[30px] [&>p:last-child]:mb-0 [&>p:last-child]:text-[14px] [&>p:last-child]:font-[850] [&>p:last-child]:tracking-[.07em] [&>p:last-child]:text-[#cbd2df] [&>p:last-child]:uppercase`,
  actionCommentsPanel: 'min-w-0 px-[5vw] pt-[72px] pb-[100px] max-[780px]:px-5 max-[780px]:pt-[50px] max-[780px]:pb-[75px]',
  commentComposer: 'mb-11 grid gap-[10px] border-2 border-paper bg-paper p-6 text-ink shadow-[6px_6px_0_var(--color-signal)] max-[780px]:px-4 max-[780px]:py-[19px] [&_label]:text-[10px] [&_label]:font-[950] [&_label]:tracking-[.09em] [&_label]:uppercase [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-none [&_textarea]:border-[1.5px] [&_textarea]:border-ink [&_textarea]:bg-white [&_textarea]:px-[14px] [&_textarea]:py-[13px] [&_textarea]:font-sans [&_textarea]:text-[15px] [&_textarea]:font-[650] [&_textarea]:leading-[1.5] [&_textarea]:text-ink [&_textarea]:outline-none [&_textarea]:focus:shadow-[3px_3px_0_var(--color-signal)]',
  commentComposerFoot: 'flex items-center justify-between gap-[15px] [&>small]:text-[10px] [&>small]:font-extrabold [&>small]:text-[#667085] [&>span]:flex [&>span]:items-center [&>span]:gap-3',
  commentSubmit: 'min-h-[42px] cursor-pointer border-0 bg-signal px-[14px] text-[10px] font-[950] tracking-[.08em] text-white shadow-[3px_3px_0_var(--color-ink)] disabled:cursor-wait disabled:opacity-55',
  commentCancel: 'cursor-pointer border-0 border-b border-current bg-transparent px-0 py-[3px] text-[10px] font-[950] tracking-[.06em] uppercase',
  commentError: 'mt-[3px] mb-0 text-[12px] font-extrabold leading-[1.4] text-[#b51f2b]',
  commentsSignIn: 'mb-11 border-2 border-[#6f788b] p-[25px] [&_strong]:text-[24px] [&_strong]:tracking-[-.035em] [&_strong]:uppercase [&_p]:mt-2 [&_p]:mb-[18px] [&_p]:text-[14px] [&_p]:font-bold [&_p]:text-[#cbd2df] [&>button]:border-paper [&>button]:text-paper [&>button:hover]:bg-paper [&>button:hover]:text-ink',
  commentsVerifyButton: 'min-h-[42px] cursor-pointer border-2 border-paper bg-transparent px-[14px] text-[10px] font-[950] tracking-[.08em] text-paper disabled:cursor-wait disabled:opacity-55 hover:bg-paper hover:text-ink',
  commentsVerifySuccess: '!mt-3 !mb-0 !text-[#a9e6ba]',
  commentsStatus: 'm-0 text-[14px] font-[750] leading-[1.5] text-[#cbd2df]',
  commentsPolicy: 'mt-[-25px] mb-11 border-l-[3px] border-signal pl-3 text-[12px] font-extrabold leading-[1.45] text-[#cbd2df]',
  commentThreadList: 'grid gap-[22px]',
  commentThreadNode: 'min-w-0 scroll-mt-6 target:outline-2 target:outline-offset-8 target:outline-signal',
  commentChildren: 'mt-[18px] mr-0 mb-0 ml-[34px] grid gap-[18px] border-l-2 border-[#525d73] pl-[18px] max-[780px]:ml-[13px] max-[780px]:pl-[11px]',
  commentCard: 'grid min-w-0 grid-cols-[48px_minmax(0,1fr)] gap-[14px]',
  commentAvatar: 'relative grid size-12 flex-none place-items-center overflow-hidden rounded-full border-2 border-paper bg-[#dfe8dd] text-[14px] font-[950] text-ink [&_img]:absolute [&_img]:inset-0 [&_img]:size-full [&_img]:object-cover',
  commentAvatarDeleted: '!border-[#6f788b] !bg-transparent text-[22px] !text-[#8e98ab]',
  commentCopy: 'min-w-0 border-b border-[#525d73] pb-[22px] [&_header]:flex [&_header]:flex-wrap [&_header]:items-start [&_header]:justify-between [&_header]:gap-x-4 [&_header]:gap-y-[7px] [&_header>strong]:text-[14px] [&_header>strong]:font-[950] [&_time]:text-[9px] [&_time]:font-[850] [&_time]:tracking-[.04em] [&_time]:text-[#8e98ab] [&_time]:uppercase [&>p]:mt-[10px] [&>p]:mb-0 [&>p]:whitespace-pre-wrap [&>p]:text-[14px] [&>p]:font-[650] [&>p]:leading-[1.55] [&>p]:text-[#eef1f7] [&>p]:[overflow-wrap:anywhere]',
  commentAuthor: 'flex flex-col items-start gap-[2px] [&_strong]:text-[14px] [&_strong]:font-[950] [&_small]:text-[11px] [&_small]:font-extrabold [&_small]:leading-none [&_small]:text-[#aeb7c7]',
  commentTombstone: '!text-[#8e98ab] italic',
  commentActions: 'mt-3 flex flex-wrap gap-[14px] [&_button]:cursor-pointer [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-0 [&_button]:py-0.5 [&_button]:text-[9px] [&_button]:font-[950] [&_button]:tracking-[.07em] [&_button]:text-[#cbd2df] [&_button]:uppercase [&_button:disabled]:cursor-wait [&_button:disabled]:opacity-55',
  commentDelete: '!text-[#ff7d86]',
  commentReported: 'py-0.5 text-[9px] font-[950] tracking-[.07em] text-[#8e98ab] uppercase',
  commentReportForm: 'mt-4 grid gap-2.5 border-l-[3px] border-signal bg-[#202b3f] p-4 [&_label]:text-[9px] [&_label]:font-[950] [&_label]:tracking-[.08em] [&_label]:text-[#cbd2df] [&_label]:uppercase [&_label_small]:ml-1 [&_label_small]:font-bold [&_label_small]:tracking-normal [&_label_small]:text-[#8e98ab] [&_label_small]:normal-case [&_select]:w-full [&_select]:border [&_select]:border-[#6f788b] [&_select]:bg-ink [&_select]:px-3 [&_select]:py-2.5 [&_select]:text-[13px] [&_select]:font-bold [&_select]:text-paper [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border [&_textarea]:border-[#6f788b] [&_textarea]:bg-ink [&_textarea]:px-3 [&_textarea]:py-2.5 [&_textarea]:text-[13px] [&_textarea]:font-semibold [&_textarea]:leading-[1.45] [&_textarea]:text-paper [&>div]:flex [&>div]:gap-3 [&_button]:cursor-pointer [&_button]:border-0 [&_button]:bg-transparent [&_button]:px-0 [&_button]:py-1 [&_button]:text-[9px] [&_button]:font-[950] [&_button]:tracking-[.07em] [&_button]:text-[#cbd2df] [&_button]:uppercase [&_button:first-child]:text-[#ff7d86]',
  commentReplyComposer: 'mt-[18px] mr-0 mb-5 ml-[62px] p-[18px] shadow-[4px_4px_0_var(--color-signal)] max-[780px]:ml-[18px]',

  orgDetailHero: 'grid grid-cols-[1.35fr_.65fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  orgDetailHeading: `${diagonalInk} min-w-0 border-r-2 border-ink px-[6vw] pt-[65px] pb-[75px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  orgDetailTitle: `${headingBase} max-w-[1050px] text-[clamp(55px,7.6vw,116px)] [overflow-wrap:anywhere] max-[780px]:text-[clamp(48px,15vw,75px)]`,
  issueDetailSummary: 'mt-[42px] mb-0 max-w-[820px] text-[clamp(18px,2vw,25px)] font-[650] leading-[1.4]',
  orgDetailWebsite: 'flex flex-col justify-center bg-ink px-[5vw] py-[70px] text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[62px] [&>a]:flex [&>a]:min-h-[62px] [&>a]:items-center [&>a]:justify-between [&>a]:gap-5 [&>a]:bg-signal [&>a]:px-[18px] [&>a]:text-[11px] [&>a]:font-[950] [&>a]:leading-[1.3] [&>a]:tracking-[.08em] [&>a]:text-white [&>a]:no-underline [&>a]:shadow-[5px_5px_0_var(--color-paper)] [&>a:hover]:translate-[3px] [&>a:hover]:shadow-[2px_2px_0_var(--color-paper)] [&>p:not(:first-child)]:m-0 [&>p:not(:first-child)]:text-[15px] [&>p:not(:first-child)]:font-bold [&>p:not(:first-child)]:text-[#cbd2df]',
  orgWebsitePreview: 'mb-[22px]',
  orgDescriptionShell: 'grid grid-cols-[minmax(220px,.55fr)_minmax(0,1.45fr)] gap-[8vw] border-b-2 border-ink px-[6vw] py-[85px] max-[780px]:grid-cols-1 max-[780px]:gap-[38px] max-[780px]:px-5 max-[780px]:py-[65px]',
  orgActionsSection: 'px-[5vw] pt-[85px] pb-[105px] max-[780px]:px-5 max-[780px]:pt-[65px] max-[780px]:pb-[75px]',
  orgDirectoryTitle: `${headingBase} text-[clamp(55px,7.4vw,108px)] [overflow-wrap:anywhere] max-[780px]:text-[clamp(50px,16vw,78px)]`,
  orgDirectorySection: 'px-[6vw] pt-[82px] pb-[110px] max-[780px]:px-5 max-[780px]:pt-[60px] max-[780px]:pb-[78px]',
  orgDirectoryList: 'm-0 list-none border-t-2 border-ink p-0',
  orgDirectoryLink: 'grid grid-cols-[minmax(0,1fr)_auto] items-center gap-8 border-b-[1.5px] border-ink px-1 py-[27px] text-ink no-underline hover:[&_h3]:text-signal focus-visible:outline-3 focus-visible:outline-offset-4 focus-visible:outline-signal focus-visible:[&_h3]:text-signal max-[780px]:grid-cols-1 max-[780px]:gap-[15px] [&_h3]:m-0 [&_h3]:text-[clamp(25px,3vw,42px)] [&_h3]:leading-[.95] [&_h3]:tracking-[-.05em] [&_h3]:uppercase [&_p]:mt-[10px] [&_p]:mb-0 [&_p]:text-[12px] [&_p]:font-extrabold [&_p]:text-[#667085] [&>span]:flex [&>span]:items-center [&>span]:gap-5 [&>span]:text-[10px] [&>span]:font-[950] [&>span]:tracking-[.08em] [&>span]:uppercase [&>span_b]:text-[20px] [&>span_b]:text-signal',

  likedHero: 'grid grid-cols-[1.3fr_.7fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  likedHeading: `${diagonalInk} min-w-0 border-r-2 border-ink px-[6vw] pt-[70px] pb-[78px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  likedTitle: `${headingBase} text-[clamp(64px,8vw,118px)] max-[780px]:text-[clamp(58px,20vw,92px)]`,
  likedHeadingCopy: 'mt-[42px] mb-0 max-w-[680px] text-[clamp(18px,2vw,24px)] font-[650] leading-[1.45]',
  likedSummary: 'flex flex-col justify-center bg-ink px-[5vw] py-[65px] text-paper max-[780px]:px-5 max-[780px]:pt-[52px] max-[780px]:pb-[60px] [&_strong]:text-[clamp(64px,8vw,112px)] [&_strong]:leading-[.8] [&_strong]:tracking-[-.07em] [&_strong]:text-signal [&_span]:mt-[18px] [&_span]:text-[15px] [&_span]:font-[750] [&_span]:leading-[1.45] [&_span]:text-[#cbd2df]',
  likedActionsSection: 'min-h-[340px] px-[5vw] pt-[70px] pb-[105px] max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[75px]',
  actionListBordered: 'border-t-2 border-ink',
  likedEmpty: 'max-w-[760px] [&_h2]:m-0 [&_h2]:text-[clamp(38px,5vw,68px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&_p]:mt-6 [&_p]:mb-0 [&_p]:text-[17px] [&_p]:font-[650] [&_p]:leading-[1.55]',

  commentsPageSection: 'min-h-[340px] px-[5vw] pt-[70px] pb-[105px] max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[75px]',
  commentsTitle: `${headingBase} text-[clamp(64px,8vw,118px)] max-[780px]:text-[clamp(52px,16vw,72px)]`,
  commentsPageList: 'm-0 grid list-none gap-0 border-t-2 border-ink p-0',
  commentHistoryCard: 'grid grid-cols-[minmax(0,1fr)_auto] gap-x-8 gap-y-5 border-b-[1.5px] border-ink px-1 py-8 max-[780px]:grid-cols-1',
  commentHistoryCopy: 'min-w-0 [&>p]:m-0 [&>p]:whitespace-pre-wrap [&>p]:text-[16px] [&>p]:font-[650] [&>p]:leading-[1.55] [&>p]:[overflow-wrap:anywhere]',
  commentHistoryMeta: 'mb-3 flex flex-wrap items-center gap-x-[10px] gap-y-1.5 [&_a]:text-[11px] [&_a]:font-[950] [&_a]:tracking-[.075em] [&_a]:text-ink [&_a]:uppercase [&_a]:underline-offset-4 [&_a:hover]:text-signal [&_time]:text-[10px] [&_time]:font-[850] [&_time]:tracking-[.055em] [&_time]:text-[#667085] [&_time]:uppercase [&_time]:before:mr-[10px] [&_time]:before:text-ink/45 [&_time]:before:content-["·"]',
  commentHistoryDeleted: '!text-[#667085] italic',
  commentHistoryLink: 'flex min-h-[42px] min-w-[158px] items-center justify-between gap-4 self-start bg-signal px-4 text-[10px] font-[950] tracking-[.08em] text-white uppercase no-underline shadow-[4px_4px_0_var(--color-ink)] transition-[transform,box-shadow] duration-150 hover:translate-[2px] hover:shadow-[2px_2px_0_var(--color-ink)] max-[780px]:w-full',
  commentsPagination: 'mt-12 flex flex-wrap items-center justify-center gap-2',
  commentsPaginationLink: 'grid min-h-10 min-w-10 place-items-center border-[1.5px] border-ink px-3 text-[11px] font-[950] tracking-[.05em] text-ink uppercase no-underline hover:bg-ink hover:text-paper',
  commentsPaginationCurrent: 'grid min-h-10 min-w-10 place-items-center bg-ink px-3 text-[11px] font-[950] text-paper',
  commentsPaginationGap: 'px-2 text-[12px] font-black text-[#667085]',

  contactShell: 'grid min-h-[calc(100vh-78px)] grid-cols-[.82fr_1.18fr] max-[780px]:grid-cols-1',
  contactHeading: `${diagonalInk} border-r-2 border-ink px-[5vw] py-[70px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  contactTitle: `${headingBase} text-[clamp(60px,7vw,108px)] max-[780px]:text-[clamp(48px,15vw,75px)]`,
  contactHeadingCopy: 'mt-[45px] mb-0 max-w-[500px] text-[17px] font-bold leading-[1.5]',
  contactPanel: 'flex items-start justify-center bg-ink px-[5vw] pt-[70px] pb-[90px] text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[70px]',
  contactForm: 'grid w-[min(100%,650px)] gap-5 [&_h2]:m-0 [&_h2]:text-[clamp(42px,5vw,68px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&_label]:grid [&_label]:gap-2 [&_label]:text-[10px] [&_label]:font-[950] [&_label]:tracking-[.1em] [&_label]:text-paper [&_label]:uppercase [&_input]:w-full [&_input]:resize-y [&_input]:rounded-none [&_input]:border-2 [&_input]:border-transparent [&_input]:bg-paper [&_input]:px-[15px] [&_input]:py-[14px] [&_input]:font-sans [&_input]:text-[16px] [&_input]:font-bold [&_input]:leading-[1.35] [&_input]:text-ink [&_input]:outline-none [&_input]:focus:border-signal [&_input]:focus:shadow-[4px_4px_0_var(--color-signal)] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-none [&_textarea]:border-2 [&_textarea]:border-transparent [&_textarea]:bg-paper [&_textarea]:px-[15px] [&_textarea]:py-[14px] [&_textarea]:font-sans [&_textarea]:text-[16px] [&_textarea]:font-bold [&_textarea]:leading-[1.35] [&_textarea]:text-ink [&_textarea]:outline-none [&_textarea]:focus:border-signal [&_textarea]:focus:shadow-[4px_4px_0_var(--color-signal)] [&_select]:w-full [&_select]:resize-y [&_select]:rounded-none [&_select]:border-2 [&_select]:border-transparent [&_select]:bg-paper [&_select]:px-[15px] [&_select]:py-[14px] [&_select]:font-sans [&_select]:text-[16px] [&_select]:font-bold [&_select]:leading-[1.35] [&_select]:text-ink [&_select]:outline-none [&_select]:focus:border-signal [&_select]:focus:shadow-[4px_4px_0_var(--color-signal)]',
  contactHoneypot: 'absolute left-[-10000px] h-px w-px overflow-hidden',
  contactToast: 'fixed top-24 right-6 z-30 w-[min(390px,calc(100vw-40px))] border-2 border-ink bg-paper px-[18px] py-[17px] text-ink shadow-[7px_7px_0_var(--color-signal)] max-[780px]:top-[82px] max-[780px]:right-[14px] max-[780px]:w-[calc(100vw-28px)] [&_strong]:mb-1 [&_strong]:block [&_strong]:text-[12px] [&_strong]:font-[950] [&_strong]:tracking-[.08em] [&_strong]:uppercase [&_span]:block [&_span]:text-[14px] [&_span]:font-[750] [&_span]:leading-[1.4]',
  contactToastSuccess: '!border-[#287a3d] !shadow-[7px_7px_0_#287a3d]',
  contactToastError: 'border-signal',

  legalHero: 'grid grid-cols-[1.15fr_.85fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  legalHeroHeading: `${diagonalInk} min-w-0 border-r-2 border-ink px-[6vw] pt-[65px] pb-[75px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  legalTitle: `${headingBase} max-w-[920px] text-[clamp(55px,7.6vw,116px)] max-[780px]:text-[clamp(48px,15vw,75px)]`,
  legalHeroCopy: 'mt-[42px] mb-0 max-w-[680px] text-[clamp(18px,2vw,24px)] font-[650] leading-[1.45]',
  legalHeroAside: 'flex flex-col justify-center bg-ink px-[5vw] py-[70px] text-paper max-[780px]:px-5 max-[780px]:pt-[52px] max-[780px]:pb-[60px] [&_strong]:max-w-[390px] [&_strong]:text-[clamp(38px,5vw,66px)] [&_strong]:leading-[.9] [&_strong]:tracking-[-.06em] [&_strong]:text-signal [&_strong]:uppercase [&_span]:mt-[22px] [&_span]:max-w-[390px] [&_span]:text-[15px] [&_span]:font-bold [&_span]:leading-[1.5] [&_span]:text-[#cbd2df]',
  legalBody: 'grid grid-cols-[minmax(190px,.48fr)_minmax(0,1.52fr)] gap-[7vw] px-[6vw] pt-[82px] pb-[105px] max-[780px]:grid-cols-1 max-[780px]:gap-[42px] max-[780px]:px-5 max-[780px]:pt-[58px] max-[780px]:pb-[75px]',
  legalToc: 'sticky top-6 grid self-start gap-[9px] max-[780px]:static max-[780px]:grid-cols-2 max-[780px]:gap-x-[18px] max-[780px]:gap-y-0 [&>p]:mb-[13px] max-[780px]:[&>p]:col-span-full [&_a]:block [&_a]:border-b-[1.5px] [&_a]:border-ink [&_a]:py-[11px] [&_a]:text-[10px] [&_a]:font-[950] [&_a]:tracking-[.09em] [&_a]:text-ink [&_a]:uppercase [&_a]:no-underline [&_a:hover]:text-signal [&_a:focus-visible]:text-signal',
  legalDocument: 'min-w-0 max-w-[860px]',
  legalSection: 'scroll-mt-[30px] border-b-[1.5px] border-line pb-[38px] max-[780px]:scroll-mt-4 [&+&]:pt-[38px] [&_h2]:mt-0 [&_h2]:mb-[18px] [&_h2]:text-[clamp(31px,4vw,50px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.055em] [&_h2]:uppercase [&_p]:m-0 [&_p]:text-[17px] [&_p]:font-[650] [&_p]:leading-[1.7] [&_p]:text-[#34405a] [&_p+p]:mt-[18px] [&_a]:font-black [&_a]:text-[#b51f2b] [&_a]:underline-offset-4',

  governmentPage: 'overflow-x-clip bg-paper',
  governmentHero: 'grid grid-cols-[1.2fr_.8fr] border-b-2 border-ink max-[780px]:grid-cols-1',
  governmentHeading: `${diagonalInk} min-w-0 [container-type:inline-size] border-r-2 border-ink px-[6vw] pt-[70px] pb-[78px] max-[780px]:border-r-0 max-[780px]:border-b-2 max-[780px]:px-5 max-[780px]:pt-[45px] max-[780px]:pb-[58px]`,
  governmentTitle: `${headingBase} max-w-full text-[clamp(32px,8cqi,68px)] leading-[.86] tracking-[-.06em] [overflow-wrap:break-word] max-[780px]:text-[clamp(32px,8cqi,68px)]`,
  governmentHeadingCopy: 'mt-[45px] mb-0 max-w-[620px] text-[clamp(18px,2vw,24px)] font-[650] leading-[1.45]',
  governmentFinderPanel: 'grid min-w-0 [container-type:inline-size] content-start gap-[22px] bg-ink px-[5vw] pt-[70px] pb-[90px] text-paper max-[780px]:px-5 max-[780px]:pt-[55px] max-[780px]:pb-[70px] [&_h2]:m-0 [&_h2]:max-w-full [&_h2]:text-[clamp(28px,9cqi,56px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&_h2]:[overflow-wrap:break-word] [&>p:not(:first-child)]:m-0 [&>p:not(:first-child)]:max-w-[520px] [&>p:not(:first-child)]:text-[16px] [&>p:not(:first-child)]:font-bold [&>p:not(:first-child)]:leading-[1.55] [&>p:not(:first-child)]:text-[#cbd2df]',
  governmentFinderForm: 'grid w-[min(100%,650px)] gap-[18px] [&_label]:grid [&_label]:gap-2 [&_label]:text-[10px] [&_label]:font-[950] [&_label]:tracking-[.1em] [&_label]:text-paper [&_label]:uppercase [&_input]:w-full [&_input]:rounded-none [&_input]:border-2 [&_input]:border-transparent [&_input]:bg-paper [&_input]:px-[15px] [&_input]:py-[14px] [&_input]:font-sans [&_input]:text-[16px] [&_input]:font-bold [&_input]:leading-[1.35] [&_input]:text-ink [&_input]:outline-none [&_input]:focus:border-signal [&_input]:focus:shadow-[4px_4px_0_var(--color-signal)]',
  governmentAddressCombobox: 'relative',
  governmentAddressPanel: 'absolute top-[calc(100%+10px)] right-0 left-0 z-[6] m-0 max-h-[min(46vh,280px)] list-none overflow-auto border-2 border-paper bg-paper p-0 text-ink shadow-[4px_4px_0_var(--color-signal)] [&_button]:grid [&_button]:w-full [&_button]:cursor-pointer [&_button]:gap-[3px] [&_button]:border-0 [&_button]:border-b [&_button]:border-line [&_button]:bg-transparent [&_button]:px-[14px] [&_button]:py-3 [&_button]:text-left [&_button]:text-ink [&_li:last-child_button]:border-b-0 [&_button:hover]:bg-ink [&_button:hover]:text-paper [&_button_strong]:text-[14px] [&_button_strong]:font-[950] [&_button_strong]:leading-[1.2] [&_button_span]:text-[12px] [&_button_span]:font-bold [&_button_span]:leading-[1.35] [&_button_span]:text-ink/72 [&_button:hover_span]:text-paper/78',
  governmentAddressActive: 'bg-ink! text-paper! [&_span]:text-paper/78!',
  governmentFinderHelp: 'm-0 max-w-[560px] text-[13px] font-bold leading-[1.45] text-[#cbd2df]',
  governmentFinderStatus: 'min-h-[1.5em] [&_p]:m-0 [&_p]:text-[14px] [&_p]:font-[750] [&_p]:leading-[1.45]',
  governmentFinderResults: 'grid gap-7 border-t-2 border-paper/18 pt-2',
  governmentFinderDistrict: 'm-0 text-[15px] font-extrabold leading-[1.45]',
  governmentFinderGroup: 'grid gap-4 [&_h3]:m-0 [&_h3]:text-[18px] [&_h3]:tracking-[-.03em] [&_h3]:uppercase',
  governmentFinderNote: 'm-0 max-w-[620px] text-[14px] font-[750] leading-[1.5] text-[#cbd2df]',
  governmentRosterShell: 'px-[5vw] pt-20 pb-[95px] max-[780px]:px-5 max-[780px]:pt-[65px] max-[780px]:pb-20',
  governmentRosterIntro: 'mb-12 max-w-[760px] [&_h2]:m-0 [&_h2]:text-[clamp(45px,6vw,82px)] [&_h2]:leading-[.87] [&_h2]:tracking-[-.07em] [&_h2]:uppercase [&>p:last-child]:mt-6 [&>p:last-child]:mb-0 [&>p:last-child]:max-w-[680px] [&>p:last-child]:text-[17px] [&>p:last-child]:font-[650] [&>p:last-child]:leading-[1.6]',
  governmentRosterEmpty: 'border-2 border-ink bg-white px-7 py-[34px] shadow-[7px_7px_0_var(--color-signal)] [&_h3]:mt-0 [&_h3]:mb-[10px] [&_h3]:text-[24px] [&_h3]:uppercase [&_p]:m-0 [&_p]:max-w-[620px] [&_p]:text-[16px] [&_p]:font-bold [&_p]:leading-[1.55]',
  governmentRosterLayout: 'grid grid-cols-[240px_minmax(0,1fr)] items-start gap-[42px] max-[780px]:grid-cols-1 max-[780px]:gap-7',
  governmentRosterNav: 'sticky top-4 max-h-[calc(100vh-32px)] overflow-auto border-2 border-ink bg-white px-[18px] py-[22px] shadow-[6px_6px_0_var(--color-ink)] max-[780px]:static max-[780px]:max-h-none max-[780px]:overflow-visible',
  rosterNavEyebrow: '!mb-[18px]',
  governmentRosterNavChamber: '[&+&]:mt-[22px] [&+&]:border-t-[1.5px] [&+&]:border-line [&+&]:pt-[18px]',
  governmentRosterNavChamberLink: 'mb-[10px] block text-[12px] font-[950] tracking-[.08em] text-ink uppercase no-underline hover:text-signal focus-visible:text-signal',
  governmentRosterNavStates: 'm-0 grid list-none gap-0.5 p-0 max-[780px]:grid-cols-[repeat(auto-fill,minmax(44px,1fr))] max-[780px]:gap-1.5 [&_a]:block [&_a]:px-2 [&_a]:py-[7px] [&_a]:text-[13px] [&_a]:font-extrabold [&_a]:leading-[1.25] [&_a]:text-ink [&_a]:no-underline [&_a:hover]:bg-ink [&_a:hover]:text-paper [&_a:focus-visible]:bg-ink [&_a:focus-visible]:text-paper max-[780px]:[&_a]:flex max-[780px]:[&_a]:min-h-10 max-[780px]:[&_a]:items-center max-[780px]:[&_a]:justify-center max-[780px]:[&_a]:border-[1.5px] max-[780px]:[&_a]:border-ink max-[780px]:[&_a]:p-0 max-[780px]:[&_a]:text-[12px] max-[780px]:[&_a]:font-[950] max-[780px]:[&_a]:tracking-[.04em]',
  governmentRosterNavStateFull: 'max-[780px]:hidden',
  governmentRosterNavStateAbbr: 'hidden max-[780px]:inline',
  governmentRosterMain: 'min-w-0',
  governmentRosterSection: 'scroll-mt-6 [&+&]:mt-[70px] [&+&]:border-t-2 [&+&]:border-line [&+&]:pt-[70px]',
  governmentRosterHeading: 'mb-[34px] [&_h2]:m-0 [&_h2]:scroll-mt-6 [&_h2]:text-[clamp(38px,5vw,64px)] [&_h2]:leading-[.9] [&_h2]:tracking-[-.06em] [&_h2]:uppercase [&>p:last-child]:mt-[18px] [&>p:last-child]:mb-0 [&>p:last-child]:max-w-[680px] [&>p:last-child]:text-[16px] [&>p:last-child]:font-[650] [&>p:last-child]:leading-[1.55]',
  governmentRosterGroups: 'grid gap-[42px]',
  governmentStateGroup: '-m-2 scroll-mt-6 p-2 target:bg-[#fff0f1] target:outline-2 target:outline-signal [&_h3]:mt-0 [&_h3]:mb-[18px] [&_h3]:text-[22px] [&_h3]:tracking-[-.03em] [&_h3]:uppercase',
  congressMemberGrid: 'grid w-full grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-[22px]',
  congressMemberCard: 'grid h-full min-w-0 grid-cols-[112px_minmax(0,1fr)] gap-4 border-2 border-ink bg-white p-5 text-ink shadow-[6px_6px_0_var(--color-ink)] [&:not(:has([data-member-photo]))]:grid-cols-1 max-[780px]:grid-cols-1',
  congressMemberPhoto: 'min-w-0 [&_img]:block [&_img]:h-auto [&_img]:w-full [&_img]:aspect-[4/5] [&_img]:border-2 [&_img]:border-ink [&_img]:object-cover',
  congressMemberPhotoCredit: 'mt-2 mb-0 text-[10px] font-bold leading-[1.35] text-ink/72 [overflow-wrap:anywhere] [word-break:break-word]',
  congressMemberBody: 'grid min-w-0 content-start gap-[10px]',
  congressMemberTitle: 'm-0 text-[10px] font-[950] tracking-[.08em] text-ink/72 uppercase',
  congressMemberName: 'm-0 text-[clamp(20px,2.1vw,28px)] leading-[1.02] tracking-[-.04em] uppercase [overflow-wrap:anywhere]',
  congressMemberMeta: "m-0 flex flex-wrap gap-x-[10px] gap-y-1.5 text-[13px] font-extrabold leading-[1.4] [&_span+span]:before:mr-[10px] [&_span+span]:before:text-ink/45 [&_span+span]:before:content-['·']",
  congressMemberLinks: 'm-0 grid list-none gap-2 p-0 [&_a]:text-[12px] [&_a]:font-black [&_a]:tracking-[.06em] [&_a]:text-[linktext] [&_a]:uppercase [&_a]:no-underline [&_a]:[overflow-wrap:anywhere] [&_a:visited]:text-[visitedtext]',
  congressMemberOffice: 'm-0 text-[13px] font-bold leading-[1.45] [overflow-wrap:anywhere]',
  congressMemberSocial: 'flex flex-wrap gap-1.5 [&_a]:inline-flex [&_a]:size-8 [&_a]:items-center [&_a]:justify-center [&_a]:text-[18px] [&_a]:text-ink [&_a]:no-underline [&_a]:transition-colors [&_a]:duration-150 [&_a:hover]:text-signal [&_a:focus-visible]:text-signal',
  reapprovalWarning: '-mt-1 mb-[3px] border-l-[5px] border-signal bg-[#fff0f1] px-[15px] py-[14px] text-[13px] font-bold leading-[1.45] text-[#a81522] [&_strong]:mb-0.5 [&_strong]:block [&_strong]:text-[11px] [&_strong]:font-[950] [&_strong]:tracking-[.04em] [&_strong]:uppercase',
} as const;
